# frozen_string_literal: true

require_relative "../test_helper"

# Golden-file tests compare our output against upstream MJML JS output.
#
# Each .mjml fixture has a corresponding .expected.html generated by
# `rake fixtures:regenerate`. We render the same MJML in Ruby and assert
# whitespace-normalized equality.
#
# If a test fails, run `rake fixtures:regenerate` to update the expected
# output, then check whether the diff is intentional.
class GoldenFileTest < Minitest::Test
  FIXTURES_DIR = File.expand_path("../fixtures", __dir__)

  Dir.glob("#{FIXTURES_DIR}/**/*.mjml").each do |mjml_path|
    expected_path = mjml_path.sub(/\.mjml$/, ".expected.html")
    next unless File.exist?(expected_path)

    # Derive test name from path: test/fixtures/mj_text/basic.mjml → test_mj_text_basic
    relative = mjml_path.delete_prefix("#{FIXTURES_DIR}/").delete_suffix(".mjml")
    test_name = "test_#{relative.tr("/", "_")}"

    define_method(test_name) do
      mjml_input = File.read(mjml_path)
      expected_html = File.read(expected_path)
      actual_html = render(mjml_input)

      assert_html_equal expected_html, actual_html,
        "Output differs from upstream JS for #{relative}.mjml"
    end
  end
end
